### ISSUE TITLE
使用 data-src 图片打包问题

### ISSUE THREAD

**Issue by P-Mz** [codexu/x-build#13]
img标签使用 data-src 图片没有被打包

**Comment by codexu** [comment]
如果没有打包可以尝试使用require()的方式引入图片文件

**Comment by P-Mz** [comment]
> 如果没有打包可以尝试使用要求（）的方式引入图片文件

![image](https://user-images.githubusercontent.com/40508526/56551190-3b9d5580-65ba-11e9-8e0e-cbe8500092ca.png)

html 中怎么require() ?

**Comment by codexu** [comment]
data-src=require("/src/...")
还有你应该使用相对路径 ./

**Comment by P-Mz** [comment]
> data-src = require（“/ src / ...”）
> 还有你应该使用相对路径./

打包前
![image](https://user-images.githubusercontent.com/40508526/56627955-8f6f7380-667a-11e9-988f-def1067e529d.png)


打包后
![image](https://user-images.githubusercontent.com/40508526/56627934-79fa4980-667a-11e9-9d3f-d7159a4135b4.png)

路径没有变化, 图片也没有被打包,  没有使用 pug 模板
