### ISSUE TITLE
请问构建报错是什么原因？

### ISSUE THREAD

**Issue by ong-ing** [codexu/x-build#141]
(macOS，已用sudo权限全局安装x-build)报错信息如下： 
- - - - - - - - - - - - x-build 6.1.0-beta.15 - - - - - - - - - - - - 

X-BUILD v6.1.0-beta.15

? 选择 UI 框架 Element Plus
? 选择 CSS 预处理器 Sass/Scss
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: ENOENT: no such file or directory, open '/Users/hl/Development/Workspace/VscProjects/vite-naive-admin/src/styles/global.ejs'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/hl/Development/Workspace/VscProjects/vite-naive-admin/src/styles/global.ejs'
}

**Comment by codexu** [comment]
抱歉，发布了错误的版本 6.1.0-beta.16 解决了这个问题。
