### ISSUE TITLE
[yarn serve] js css执行顺序问题

### ISSUE THREAD

**Issue by LOUSANPANG** [codexu/x-build#17]
**项目运行后css js 执行顺序问题**
1. 需要获取DOM元素的 `offsetTop`属性。
2. 必须设置DOM元素的宽高。
3. js 优于 css 导致DOM元素`offsetTop`属性为固定值。
<br/>

**示例截图**

![image](https://user-images.githubusercontent.com/36870764/62424850-34342f00-b707-11e9-87de-1bece24d9fb9.png)
<br/>

**期望**

* 项目运行后css 优于 js代码包执行
![image](https://user-images.githubusercontent.com/36870764/62424874-6c3b7200-b707-11e9-9e83-7022c8838ded.png)
<br/>

**版本信息:**

 - OS: [iOS10.14.5]
 - Version [5.1.3]
<br/>

**奖励**

 - 🌹

**Comment by codexu** [comment]
开发模式中 css 并没有单独拆分，相当于所有的 js 加载完成后才会把 css 插入到 <style> 标签中
