### ISSUE TITLE
8080端口被占用会启动失败

### ISSUE THREAD

**Issue by pinguo-laihouxin** [codexu/x-build#19]
大佬你好，使用过程中发现如果8080端口被其他项目先占用了，`yarn serve` 会直接失败，能不能做成像vue-cli一样，如果8080占用了自动启动到8081端口上，以此类推，现实开发中这样同时启动几个项目的场景还是挺常见的

**Comment by codexu** [comment]
感谢你的建议，我会抽空补充这块功能，并通知你
