### ISSUE TITLE
npm install时报错

### ISSUE THREAD

**Issue by zhaolijun8** [codexu/x-build#5]
npm WARN deprecated babel-preset-es2015@6.24.1: ????  Thanks for using Babel: we
 recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@n
pmjs.com for more info.
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for comp
atibility with current and future versions of Node.js
npm WARN tarball tarball data for caniuse-lite@^1.0.30000839 (sha1-3nyEzeBYIUPPT
1q98bmOWgU5rUo=) seems to be corrupted. Trying one more time.
npm WARN x-build@4.3.1 No repository field.

npm ERR! path E:\x-build\node_modules\.staging\caniuse-lite-f36f1fca\data\featur
es\css-rebeccapurple.js
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'E:\x-build\node_modules\
.staging\caniuse-lite-f36f1fca\data\features\css-rebeccapurple.js'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'E:\x-build\node_modul
es\.staging\caniuse-lite-f36f1fca\data\features\css-rebeccapurple.js'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'E:\x-build\node_mod
ules\.staging\caniuse-lite-f36f1fca\data\features\css-rebeccapurple.js'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path: 'E:\\x-build\\node_modules\\.staging\\caniuse-lite-f36f1fca\
\data\\features\\css-rebeccapurple.js' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'E:\\x-build\\
node_modules\\.staging\\caniuse-lite-f36f1fca\\data\\features\\css-rebeccapurple
.js\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'E:\\x-build\\node_modules\\.staging\\caniuse-lite-f36f1fca\\da
ta\\features\\css-rebeccapurple.js',
npm ERR!   parent: 'x-build' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or ant
ivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!

**Comment by codexu** [comment]
正常安装应该是没有问题的，你可以考虑使用cnpm或者yarn去安装依赖
