### ISSUE TITLE
pug模板支持动态渲染吗？

### ISSUE THREAD

**Issue by dumuchenglin123** [codexu/x-build#9]
就是，我从后台http请求后获得数据想把数据渲染在pug模板里面应该怎么样操作，我是想用pug.compile()方法渲染，再把获取的html字符串返给要给的节点上，但奈何在src/script/index.js 里引用pug包报错.....

![image](https://user-images.githubusercontent.com/20918639/50817790-f84b0e00-135f-11e9-9599-e167b544f374.png)
请教正确的姿势！

**Comment by codexu** [comment]
我研究了一下，没找到很好的解决办法，如果想渲染数据，尝试使用vue吧，这里使用pug完全是为了使用他的语法
